/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniproject_ndkproject_MainActivity */

#ifndef _Included_jniproject_ndkproject_MainActivity
#define _Included_jniproject_ndkproject_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniproject_ndkproject_MainActivity
 * Method:    nativeMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jniproject_ndkproject_MainActivity_nativeMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
